class ChatModel {
  final String name;
  final String message;
  final String time;
  final String avatar;
  final int unread;

  ChatModel({this.name, this.message, this.time, this.avatar, this.unread});
}

List<ChatModel> dummyData = [
  ChatModel(
    name: "Motu Patlu",
    message: "Hi, How Can I Help?",
    time: "2 Hours Ago",
    avatar: "https://picsum.photos/500/500.jpg",
    unread: 9,
  ),
  ChatModel(
    name: "Micky Mouse",
    message: "Hi, How Can I Help?",
    time: "3 Hours Ago",
    avatar: "https://picsum.photos/600/600.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Donuld Trump",
    message: "Hi, How Can I Help?",
    time: "4 Hours Ago",
    avatar: "https://picsum.photos/700/700.jpg",
    unread: 4,
  ),
  ChatModel(
    name: "Christopher Nolan",
    message: "Hi, How Can I Help?",
    time: "5 Hours Ago",
    avatar: "https://picsum.photos/800/800.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Motu Patlu",
    message: "Hi, How Can I Help?",
    time: "2 Hours Ago",
    avatar: "https://picsum.photos/500/500.jpg",
    unread: 2,
  ),
  ChatModel(
    name: "Micky Mouse",
    message: "Hi, How Can I Help?",
    time: "3 Hours Ago",
    avatar: "https://picsum.photos/600/600.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Donuld Trump",
    message: "Hi, How Can I Help?",
    time: "4 Hours Ago",
    avatar: "https://picsum.photos/700/700.jpg",
    unread: 4,
  ),
  ChatModel(
    name: "Christopher Nolan",
    message: "Hi, How Can I Help?",
    time: "5 Hours Ago",
    avatar: "https://picsum.photos/800/800.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Motu Patlu",
    message: "Hi, How Can I Help?",
    time: "2 Hours Ago",
    avatar: "https://picsum.photos/500/500.jpg",
    unread: 2,
  ),
  ChatModel(
    name: "Micky Mouse",
    message: "Hi, How Can I Help?",
    time: "3 Hours Ago",
    avatar: "https://picsum.photos/600/600.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Donuld Trump",
    message: "Hi, How Can I Help?",
    time: "4 Hours Ago",
    avatar: "https://picsum.photos/700/700.jpg",
    unread: 4,
  ),
  ChatModel(
    name: "Christopher Nolan",
    message: "Hi, How Can I Help?",
    time: "5 Hours Ago",
    avatar: "https://picsum.photos/800/800.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Motu Patlu",
    message: "Hi, How Can I Help?",
    time: "2 Hours Ago",
    avatar: "https://picsum.photos/500/500.jpg",
    unread: 2,
  ),
  ChatModel(
    name: "Micky Mouse",
    message: "Hi, How Can I Help?",
    time: "3 Hours Ago",
    avatar: "https://picsum.photos/600/600.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Donuld Trump",
    message: "Hi, How Can I Help?",
    time: "4 Hours Ago",
    avatar: "https://picsum.photos/700/700.jpg",
    unread: 4,
  ),
  ChatModel(
    name: "Motu Patlu",
    message: "Hi, How Can I Help?",
    time: "2 Hours Ago",
    avatar: "https://picsum.photos/500/500.jpg",
    unread: 9,
  ),
  ChatModel(
    name: "Micky Mouse",
    message: "Hi, How Can I Help?",
    time: "3 Hours Ago",
    avatar: "https://picsum.photos/600/600.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Donuld Trump",
    message: "Hi, How Can I Help?",
    time: "4 Hours Ago",
    avatar: "https://picsum.photos/700/700.jpg",
    unread: 4,
  ),
  ChatModel(
    name: "Christopher Nolan",
    message: "Hi, How Can I Help?",
    time: "5 Hours Ago",
    avatar: "https://picsum.photos/800/800.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Motu Patlu",
    message: "Hi, How Can I Help?",
    time: "2 Hours Ago",
    avatar: "https://picsum.photos/500/500.jpg",
    unread: 2,
  ),
  ChatModel(
    name: "Micky Mouse",
    message: "Hi, How Can I Help?",
    time: "3 Hours Ago",
    avatar: "https://picsum.photos/600/600.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Donuld Trump",
    message: "Hi, How Can I Help?",
    time: "4 Hours Ago",
    avatar: "https://picsum.photos/700/700.jpg",
    unread: 4,
  ),
  ChatModel(
    name: "Christopher Nolan",
    message: "Hi, How Can I Help?",
    time: "5 Hours Ago",
    avatar: "https://picsum.photos/800/800.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Motu Patlu",
    message: "Hi, How Can I Help?",
    time: "2 Hours Ago",
    avatar: "https://picsum.photos/500/500.jpg",
    unread: 2,
  ),
  ChatModel(
    name: "Micky Mouse",
    message: "Hi, How Can I Help?",
    time: "3 Hours Ago",
    avatar: "https://picsum.photos/600/600.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Donuld Trump",
    message: "Hi, How Can I Help?",
    time: "4 Hours Ago",
    avatar: "https://picsum.photos/700/700.jpg",
    unread: 4,
  ),
  ChatModel(
    name: "Christopher Nolan",
    message: "Hi, How Can I Help?",
    time: "5 Hours Ago",
    avatar: "https://picsum.photos/800/800.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Motu Patlu",
    message: "Hi, How Can I Help?",
    time: "2 Hours Ago",
    avatar: "https://picsum.photos/500/500.jpg",
    unread: 2,
  ),
  ChatModel(
    name: "Micky Mouse",
    message: "Hi, How Can I Help?",
    time: "3 Hours Ago",
    avatar: "https://picsum.photos/600/600.jpg",
    unread: 0,
  ),
  ChatModel(
    name: "Donuld Trump",
    message: "Hi, How Can I Help?",
    time: "4 Hours Ago",
    avatar: "https://picsum.photos/700/700.jpg",
    unread: 4,
  ),
  ChatModel(
    name: "Christopher Nolan",
    message: "Hi, How Can I Help?",
    time: "5 Hours Ago",
    avatar: "https://picsum.photos/800/800.jpg",
    unread: 0,
  )
];
